" ---- copied from global vimrc -------------------------------------------
scriptencoding utf-8
set nocompatible
set backspace=2
set history=200
set ruler
set viminfo='20,\"500
set numberwidth=3
set modeline
if &fileencodings !~? "ucs-bom"
  set fileencodings^=ucs-bom
endif
if &fileencodings !~? "utf-8"
  let g:added_fenc_utf8 = 1
  set fileencodings+=utf-8
endif
if &fileencodings !~? "default"
  set fileencodings+=default
endif
if &term ==? "xterm"
  set t_Sb=^[4%dm
  set t_Sf=^[3%dm
  set ttymouse=xterm2
endif
if &term ==? "gnome" && has("eval")
  exec "set <C-Left>=\eO5D"
  exec "set <C-Right>=\eO5C"
endif
if "" == &shell
  if executable("/bin/bash")
    set shell=/bin/bash
  elseif executable("/bin/sh")
    set shell=/bin/sh
  endif
endif
if has("eval")
  let is_bash=1
endif

" ---- my settings --------------------------------------------------------
if isdirectory($HOME . "/.vim/bundle")
    execute pathogen#infect()
endif
syntax on
filetype plugin on
filetype indent on

" various settings
set cinoptions=l1,g0,N-s
if has ("unnamedplus")
    set clipboard=unnamedplus
else
    set clipboard=unnamed
endif
set background=light
set colorcolumn=+0
set cursorline
set diffopt=filler,iwhite,context:2
set display+=uhex
set fillchars=vert:║,fold:═,diff:░
set listchars=tab:»·,trail:·,extends:❯,precedes:❮,nbsp:␣
set showbreak=↪
set formatoptions+=12nj
set formatoptions-=t
set grepprg=grep\ -nH\ $*
set hlsearch incsearch
set laststatus=2
set matchpairs+==:;
set mouse=a
if has("mouse_sgr")
    set ttymouse=sgr
endif
set nowrap
set number
set pdev=pdf
set popt=left:10mm,right:10mm,top:10mm,bottom:15mm,syntax:y,number:y,wrap:y,paper:A4
set report=0
set scrolloff=12
set showcmd
set showmatch
set sidescrolloff=20
set statusline=%f\ %y\ \{%{&ff}\}%(\ [%M%R]%)%=%{strftime(\"\%F\ \%T\",getftime(expand(\"\%\%\")))}%10.(%l:%c%)%6.p%%
set textwidth=100
set ts=4 sw=4 sts=4 expandtab
set wildignore=*.o,*.aux,*.dvi,*.pdf
set wildmenu
set wildmode=longest:full

let c_no_curly_error = 1
let g:netrw_list_hide='^\.[^.].*,.*\~$,.*\.swp,.*\.bak'
let g:tex_flavor='latex'

" abbreviations & commands
cabbr help vert help
nmap <C-H> :nohl<CR>
imap <C-H> <ESC>:nohl<CR>i
imap <C-W><Left> <ESC><C-W><Left>i
imap <C-W><Right> <ESC><C-W><Right>i
imap <C-W><Up> <ESC><C-W><Up>i
imap <C-W><Down> <ESC><C-W><Down>i
cnoremap w!! w !sudo tee % >/dev/null
" note: ctrl-/ is registered as <C-_>
nmap <C-_> <Leader>c<space>
vmap <C-_> <Leader>c<space>
imap <C-_> <ESC><Leader>c<space>i

" plugin settings
" * multi_cursor
let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0
" * flake8
let g:flake8_quickfix_height=10
let g:flake8_show_in_gutter=1
" * haskellmode
let g:haddock_browser="/usr/bin/firefox"
let g:haskell_classic_highlighting=1
" * nerdcommenter
let g:NERDCompactSexyComs = 1
let g:NERDAltDelims_c = 1
let g:NERDSpaceDelims = 1

" syntax fixes
syn match Error '\s\+$'
hi ColorColumn ctermbg=darkgrey
hi CursorLine cterm=none ctermbg=darkgrey
hi CursorLineNr ctermfg=yellow ctermbg=darkgrey cterm=inverse,bold
hi DiffAdd ctermbg=darkgray ctermfg=green
hi DiffChange ctermbg=darkgray
hi DiffDelete ctermbg=darkgray ctermfg=red cterm=none
hi DiffText ctermbg=none cterm=standout,bold
hi LineNr ctermbg=darkgray
hi Folded ctermbg=darkgray ctermfg=magenta cterm=bold
hi Constant ctermfg=red cterm=bold
hi String ctermfg=red cterm=none

" filetype-dependent
au! FileType make setlocal noexpandtab
au! BufNewFile,BufRead *.j setlocal filetype=jasmin
au! BufNewFile,BufRead *.ll setlocal filetype=llvm
au! BufNewFile,BufRead *.g setlocal filetype=antlr3
au! BufNewFile,BufRead *.lat setlocal filetype=java
au! BufNewFile,BufRead *.asm setlocal filetype=nasm
au BufNewFile,BufRead *.bolt setlocal filetype=bolt
au BufNewFile,BufRead rules.json setlocal filetype=firebase-rules
au FileType python iabbr IPDB import ipdb; ipdb.set_trace()
au FileType python iabbr IPDTRY import ipdb; with ipdb.launch_ipdb_on_exception():
au FileType javascript nnoremap <silent><F7> :JSHint<CR>
